# Generated by Django 6.0.3 on 2026-03-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("company_description", models.TextField()),
                ("job_type", models.CharField(max_length=50)),
                ("vacancies", models.IntegerField()),
                ("required_skills", models.TextField()),
                ("salary", models.CharField(max_length=30)),
                ("deadline", models.DateField()),
                ("experience_required", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
